# Stage 1: Build the Go app
FROM golang:1.18-alpine as builder

WORKDIR /app

# Copy the go.mod and go.sum files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application's source code
COPY . .

# Build the application (using the cmd/api directory)
RUN go build -o /aqua-gateway ./cmd/api/main.go

# Stage 2: Create a minimal image to run the Go application
FROM alpine:latest

WORKDIR /root/

# Copy the Go app from the builder stage
COPY --from=builder /aqua-gateway .

# Run the Go app
CMD ["./aqua-gateway"]